app:
    resource: "@AppBundle/Controller/"
    type: rest
    prefix: /api
    
api_login_check:
    path: /api/login_check
   
places:
    type:     rest
    resource: AppBundle\Controller\PlaceController
    
users:
    type:     rest
    resource: AppBundle\Controller\UserController
    
auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController
