AppBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50
        attributes:
            id:
                groups: ['user', 'preference', 'auth-token']
            firstname:
                groups: ['user', 'preference', 'auth-token']
            lastname:
                groups: ['user', 'preference', 'auth-token']
            email:
                groups: ['user', 'preference', 'auth-token']
            preferences:
                groups: ['user']

AppBundle\Entity\AuthToken:
        attributes:
            id:
                groups: ['auth-token']
            value:
                groups: ['auth-token']
            createdAt:
                groups: ['auth-token']
            user:
                groups: ['auth-token']
